-- Create user_watchlist table
create table if not exists user_watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  company_id bigint not null references companies(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, company_id)
);

-- Create alerts table
create table if not exists alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  company_id bigint not null references companies(id),
  type text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table user_watchlist enable row level security;
alter table alerts enable row level security;

-- Policies for user_watchlist
create policy "Users can view their own watchlist"
  on user_watchlist for select
  using (auth.uid() = user_id);

create policy "Users can insert into their own watchlist"
  on user_watchlist for insert
  with check (auth.uid() = user_id);

create policy "Users can delete from their own watchlist"
  on user_watchlist for delete
  using (auth.uid() = user_id);

-- Policies for alerts
create policy "Users can view their own alerts"
  on alerts for select
  using (auth.uid() = user_id);

create policy "Users can update their own alerts (mark as read)"
  on alerts for update
  using (auth.uid() = user_id);
